/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view_adm.MenuPrincipal;

import view.*;
import Validacoes.Deletar;
import Validacoes.Restaurar;
import Validacoes.Validar;
import connection.ConnectionFactory;
import java.awt.Color;
import java.awt.Font;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableRowSorter;
import model.bean.Paciente;
import model.bean.Telefone;
import model.bean.Vw_TelefonesPacientes;
import model.dao.PacienteDAO;
import model.dao.TelefoneDAO;
import model.dao.ViewsDAO;
import util.Util;

/**
 *
 * @author guimu
 */
public class ManterPacienteAdm extends javax.swing.JFrame {

    private boolean telefones = false;
    private boolean fone2 = false;
    private int codigopaciente = -1;

    public ManterPacienteAdm() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("pmaiconemenor.png")));
        BtnManterPaciente.setEnabled(false);
        BtnVisuAlterarDados.setEnabled(false);
        BtnExcluirPaciente.setEnabled(false);
        DefaultTableModel dtmPacientes = (DefaultTableModel) JTPacientes.getModel();
        TableColumnModel cmod = JTPacientes.getColumnModel();
        cmod.removeColumn(cmod.getColumn(0));
        JTPacientes.setRowSorter(new TableRowSorter(dtmPacientes));

        ReadJTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ModalAlterarResolucaoMenor = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        txtNome5 = new javax.swing.JTextField();
        LabelNome3 = new javax.swing.JLabel();
        PainelIdentificacaoPessoal7 = new javax.swing.JPanel();
        BtnSalvarAlteracoesNovo3 = new javax.swing.JButton();
        BtnCancelar3 = new javax.swing.JButton();
        jLabel60 = new javax.swing.JLabel();
        LabelEmail5 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        txtEmail4 = new javax.swing.JTextField();
        LabelCPF4 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        LabelEstadoCivil4 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        estadocivil4 = new javax.swing.JComboBox<String>();
        jLabel84 = new javax.swing.JLabel();
        Sexo4 = new javax.swing.JComboBox<>();
        jEImagePanel8 = new LIB.JEImagePanel();
        jLabel85 = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        DataNasc4 = new com.github.lgooddatepicker.components.DatePicker();
        LabelCidade12 = new javax.swing.JLabel();
        TxtCidade4 = new javax.swing.JTextField();
        jLabel87 = new javax.swing.JLabel();
        TxtEndereco4 = new javax.swing.JTextField();
        jLabel88 = new javax.swing.JLabel();
        LabelProfissao4 = new javax.swing.JLabel();
        TxtProfissao4 = new javax.swing.JTextField();
        LabelReligiao4 = new javax.swing.JLabel();
        TxtReligiao4 = new javax.swing.JTextField();
        LabelEscolaridade4 = new javax.swing.JLabel();
        TxtEscolaridade4 = new javax.swing.JTextField();
        LabelCidade13 = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();
        TxtTelefone10 = new javax.swing.JTextField();
        LabelCidade14 = new javax.swing.JLabel();
        TxtTelefone11 = new javax.swing.JTextField();
        jLabel90 = new javax.swing.JLabel();
        jLabel91 = new javax.swing.JLabel();
        PainelIdentificacaoPessoal8 = new javax.swing.JPanel();
        txtCPF4 = new javax.swing.JFormattedTextField();
        JCBDeletado = new javax.swing.JComboBox<String>();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new JPanel();
        jEImagePanel1 = new LIB.JEImagePanel();
        jLabel6 = new javax.swing.JLabel();
        txtBusca = new javax.swing.JTextField();
        BtnBuscar = new javax.swing.JButton();
        BtnVisuAlterarDados = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        JTPacientes = new javax.swing.JTable();
        BtnExcluirPaciente = new javax.swing.JButton();
        PainelMenu = new javax.swing.JPanel();
        BtnInicio = new javax.swing.JButton();
        BtnManterPaciente = new javax.swing.JButton();
        BtnManterConsulta = new javax.swing.JButton();
        BtnManterPsicologo = new javax.swing.JButton();
        BtnSair = new javax.swing.JButton();

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        txtNome5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtNome5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNome5ActionPerformed(evt);
            }
        });
        txtNome5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNome5KeyTyped(evt);
            }
        });

        LabelNome3.setText("Nome:");
        LabelNome3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        PainelIdentificacaoPessoal7.setBackground(new java.awt.Color(59, 131, 117));

        BtnSalvarAlteracoesNovo3.setText("Salvar Alterações");
        BtnSalvarAlteracoesNovo3.setBackground(new java.awt.Color(0, 112, 186));
        BtnSalvarAlteracoesNovo3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BtnSalvarAlteracoesNovo3.setForeground(new java.awt.Color(255, 255, 255));
        BtnSalvarAlteracoesNovo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalvarAlteracoesNovo3ActionPerformed(evt);
            }
        });

        BtnCancelar3.setText("Cancelar");
        BtnCancelar3.setBackground(new java.awt.Color(255, 153, 153));
        BtnCancelar3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BtnCancelar3.setForeground(new java.awt.Color(255, 255, 255));
        BtnCancelar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelar3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelIdentificacaoPessoal7Layout = new javax.swing.GroupLayout(PainelIdentificacaoPessoal7);
        PainelIdentificacaoPessoal7.setLayout(PainelIdentificacaoPessoal7Layout);
        PainelIdentificacaoPessoal7Layout.setHorizontalGroup(
            PainelIdentificacaoPessoal7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelIdentificacaoPessoal7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnCancelar3)
                .addGap(18, 18, 18)
                .addComponent(BtnSalvarAlteracoesNovo3, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PainelIdentificacaoPessoal7Layout.setVerticalGroup(
            PainelIdentificacaoPessoal7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelIdentificacaoPessoal7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PainelIdentificacaoPessoal7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnSalvarAlteracoesNovo3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnCancelar3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel60.setText("*");
        jLabel60.setBackground(new java.awt.Color(255, 0, 0));
        jLabel60.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(255, 0, 0));

        LabelEmail5.setText("E-mail:");
        LabelEmail5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel61.setText("*");
        jLabel61.setBackground(new java.awt.Color(255, 0, 0));
        jLabel61.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(255, 0, 0));

        txtEmail4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        LabelCPF4.setText("CPF:");
        LabelCPF4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel62.setText("*");
        jLabel62.setBackground(new java.awt.Color(255, 0, 0));
        jLabel62.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(255, 0, 0));

        LabelEstadoCivil4.setText("Estado Civil:");
        LabelEstadoCivil4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel83.setText("*");
        jLabel83.setBackground(new java.awt.Color(255, 0, 0));
        jLabel83.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel83.setForeground(new java.awt.Color(255, 0, 0));

        estadocivil4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Casado","Divorciado","Separado","Solteiro" ,"Viuvo" }));
        estadocivil4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        estadocivil4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadocivil4ActionPerformed(evt);
            }
        });

        jLabel84.setText("Sexo:");
        jLabel84.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        Sexo4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Feminino", "Masculino", "Não Definido"}));
        Sexo4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Sexo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sexo4ActionPerformed(evt);
            }
        });

        jEImagePanel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/simboloma.png"))); // NOI18N

        javax.swing.GroupLayout jEImagePanel8Layout = new javax.swing.GroupLayout(jEImagePanel8);
        jEImagePanel8.setLayout(jEImagePanel8Layout);
        jEImagePanel8Layout.setHorizontalGroup(
            jEImagePanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 272, Short.MAX_VALUE)
        );
        jEImagePanel8Layout.setVerticalGroup(
            jEImagePanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        jLabel85.setText("Data de Nascimento: ");
        jLabel85.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel86.setText("*");
        jLabel86.setBackground(new java.awt.Color(255, 0, 0));
        jLabel86.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel86.setForeground(new java.awt.Color(255, 0, 0));

        DataNasc4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        DataNasc4.setPreferredSize(new java.awt.Dimension(160, 17));

        LabelCidade12.setText("Cidade:");
        LabelCidade12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        TxtCidade4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel87.setText("Endereço:");
        jLabel87.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        TxtEndereco4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel88.setText("Alterar Dados do Paciente");
        jLabel88.setFont(new java.awt.Font("Tahoma", 0, 45)); // NOI18N
        jLabel88.setForeground(new java.awt.Color(59, 131, 117));

        LabelProfissao4.setText("Profissão:");
        LabelProfissao4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        TxtProfissao4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        LabelReligiao4.setText("Religião:");
        LabelReligiao4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        TxtReligiao4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        LabelEscolaridade4.setText("Escolaridade:");
        LabelEscolaridade4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        TxtEscolaridade4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        TxtEscolaridade4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtEscolaridade4ActionPerformed(evt);
            }
        });

        LabelCidade13.setText("Telefone1:");
        LabelCidade13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel89.setText("*");
        jLabel89.setBackground(new java.awt.Color(255, 0, 0));
        jLabel89.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel89.setForeground(new java.awt.Color(255, 0, 0));

        TxtTelefone10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        TxtTelefone10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtTelefone10ActionPerformed(evt);
            }
        });
        TxtTelefone10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtTelefone10KeyTyped(evt);
            }
        });

        LabelCidade14.setText("Telefone2:");
        LabelCidade14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        TxtTelefone11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        TxtTelefone11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtTelefone11KeyTyped(evt);
            }
        });

        jLabel90.setText("Campos Obrigatórios");
        jLabel90.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel91.setText("*");
        jLabel91.setBackground(new java.awt.Color(255, 0, 0));
        jLabel91.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel91.setForeground(new java.awt.Color(255, 0, 0));

        PainelIdentificacaoPessoal8.setBackground(new java.awt.Color(59, 131, 117));

        javax.swing.GroupLayout PainelIdentificacaoPessoal8Layout = new javax.swing.GroupLayout(PainelIdentificacaoPessoal8);
        PainelIdentificacaoPessoal8.setLayout(PainelIdentificacaoPessoal8Layout);
        PainelIdentificacaoPessoal8Layout.setHorizontalGroup(
            PainelIdentificacaoPessoal8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 811, Short.MAX_VALUE)
        );
        PainelIdentificacaoPessoal8Layout.setVerticalGroup(
            PainelIdentificacaoPessoal8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        try {
            txtCPF4.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCPF4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtCPF4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCPF4KeyTyped(evt);
            }
        });

        JCBDeletado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sim", "Não" }));

        jLabel1.setText("Paciente Deletado?");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelIdentificacaoPessoal7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jEImagePanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel88, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel60)
                                    .addComponent(jLabel61)
                                    .addComponent(jLabel83)
                                    .addComponent(jLabel86)
                                    .addComponent(jLabel89))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LabelEmail5)
                                            .addComponent(LabelNome3))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(txtEmail4, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel62)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel84)
                                                    .addComponent(LabelCPF4))
                                                .addGap(27, 27, 27)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(Sexo4, 0, 247, Short.MAX_VALUE)
                                                    .addComponent(txtCPF4)))
                                            .addComponent(txtNome5)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(LabelEstadoCivil4)
                                        .addGap(18, 18, 18)
                                        .addComponent(estadocivil4, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel85)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(DataNasc4, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(LabelCidade12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(TxtCidade4, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(LabelProfissao4)
                                                .addComponent(jLabel87))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(TxtProfissao4, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
                                                .addComponent(TxtEndereco4)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(LabelEscolaridade4)
                                                .addComponent(LabelCidade13, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(JCBDeletado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(TxtTelefone10, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                                                        .addComponent(TxtEscolaridade4))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(LabelCidade14)
                                                        .addComponent(LabelReligiao4))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(TxtReligiao4, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(TxtTelefone11, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel91)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel90))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PainelIdentificacaoPessoal8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(17, Short.MAX_VALUE)
                        .addComponent(jLabel88, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jEImagePanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNome3)
                    .addComponent(txtNome5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel60))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelEmail5)
                    .addComponent(jLabel61)
                    .addComponent(txtEmail4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelCPF4)
                    .addComponent(jLabel62)
                    .addComponent(txtCPF4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelEstadoCivil4)
                    .addComponent(jLabel83)
                    .addComponent(estadocivil4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel84)
                    .addComponent(Sexo4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel85)
                    .addComponent(jLabel86)
                    .addComponent(DataNasc4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelCidade12)
                    .addComponent(TxtCidade4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel87)
                    .addComponent(TxtEndereco4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelProfissao4)
                    .addComponent(TxtProfissao4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelReligiao4)
                    .addComponent(TxtReligiao4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelEscolaridade4)
                    .addComponent(TxtEscolaridade4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelCidade13, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(jLabel89)
                    .addComponent(TxtTelefone10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelCidade14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TxtTelefone11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JCBDeletado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(1, 1, 1)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel90)
                    .addComponent(jLabel91))
                .addGap(32, 32, 32)
                .addComponent(PainelIdentificacaoPessoal7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(168, 168, 168)
                    .addComponent(PainelIdentificacaoPessoal8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(392, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout ModalAlterarResolucaoMenorLayout = new javax.swing.GroupLayout(ModalAlterarResolucaoMenor.getContentPane());
        ModalAlterarResolucaoMenor.getContentPane().setLayout(ModalAlterarResolucaoMenorLayout);
        ModalAlterarResolucaoMenorLayout.setHorizontalGroup(
            ModalAlterarResolucaoMenorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ModalAlterarResolucaoMenorLayout.setVerticalGroup(
            ModalAlterarResolucaoMenorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(59, 131, 117));
        jPanel1.setForeground(new java.awt.Color(59, 131, 117));
        jPanel1.setPreferredSize(new java.awt.Dimension(1080, 89));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1920, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 89, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        jEImagePanel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/spring-floral-watercolor-background-vector-green-with-leaf-illustration_53876-126350.jpg"))); // NOI18N

        jLabel6.setText("Buscar Paciente por");

        txtBusca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscaKeyTyped(evt);
            }
        });

        BtnBuscar.setText("Buscar");
        BtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarActionPerformed(evt);
            }
        });

        BtnVisuAlterarDados.setText("Visualizar/ Alterar Dados");
        BtnVisuAlterarDados.setBackground(new java.awt.Color(204, 204, 204));
        BtnVisuAlterarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVisuAlterarDadosActionPerformed(evt);
            }
        });

        JTPacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome Completo", "Email", "Telefone 1", "Telefone 2", "Deletado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JTPacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTPacientesMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JTPacientesMousePressed(evt);
            }
        });
        JTPacientes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JTPacientesKeyReleased(evt);
            }
        });
        jScrollPane4.setViewportView(JTPacientes);
        if (JTPacientes.getColumnModel().getColumnCount() > 0) {
            JTPacientes.getColumnModel().getColumn(0).setResizable(false);
            JTPacientes.getColumnModel().getColumn(1).setResizable(false);
            JTPacientes.getColumnModel().getColumn(2).setResizable(false);
            JTPacientes.getColumnModel().getColumn(4).setResizable(false);
            JTPacientes.getColumnModel().getColumn(5).setResizable(false);
        }

        BtnExcluirPaciente.setText("Excluir");
        BtnExcluirPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExcluirPacienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jEImagePanel1Layout = new javax.swing.GroupLayout(jEImagePanel1);
        jEImagePanel1.setLayout(jEImagePanel1Layout);
        jEImagePanel1Layout.setHorizontalGroup(
            jEImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jEImagePanel1Layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addGroup(jEImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jEImagePanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(171, 171, 171))
                    .addGroup(jEImagePanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 853, Short.MAX_VALUE)
                        .addGap(62, 62, 62)
                        .addGroup(jEImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BtnVisuAlterarDados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnExcluirPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(336, Short.MAX_VALUE))
        );
        jEImagePanel1Layout.setVerticalGroup(
            jEImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jEImagePanel1Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(jEImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnBuscar))
                .addGroup(jEImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jEImagePanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jEImagePanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(BtnVisuAlterarDados)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnExcluirPaciente)))
                .addContainerGap(400, Short.MAX_VALUE))
        );

        getContentPane().add(jEImagePanel1, java.awt.BorderLayout.CENTER);

        PainelMenu.setBackground(new java.awt.Color(102, 102, 102));
        PainelMenu.setForeground(new java.awt.Color(102, 102, 102));

        BtnInicio.setText("Início");
        BtnInicio.setBackground(new java.awt.Color(102, 102, 102));
        BtnInicio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BtnInicio.setForeground(new java.awt.Color(255, 255, 255));
        BtnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInicioActionPerformed(evt);
            }
        });

        BtnManterPaciente.setText("Pacientes");
        BtnManterPaciente.setBackground(new java.awt.Color(102, 102, 102));
        BtnManterPaciente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BtnManterPaciente.setForeground(new java.awt.Color(255, 255, 255));
        BtnManterPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnManterPacienteActionPerformed(evt);
            }
        });

        BtnManterConsulta.setText("Consultas");
        BtnManterConsulta.setBackground(new java.awt.Color(102, 102, 102));
        BtnManterConsulta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BtnManterConsulta.setForeground(new java.awt.Color(255, 255, 255));
        BtnManterConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnManterConsultaActionPerformed(evt);
            }
        });

        BtnManterPsicologo.setText("Psicólogos");
        BtnManterPsicologo.setBackground(new java.awt.Color(102, 102, 102));
        BtnManterPsicologo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BtnManterPsicologo.setForeground(new java.awt.Color(255, 255, 255));
        BtnManterPsicologo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnManterPsicologoActionPerformed(evt);
            }
        });

        BtnSair.setText("Sair");
        BtnSair.setBackground(new java.awt.Color(102, 102, 102));
        BtnSair.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BtnSair.setForeground(new java.awt.Color(255, 255, 255));
        BtnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelMenuLayout = new javax.swing.GroupLayout(PainelMenu);
        PainelMenu.setLayout(PainelMenuLayout);
        PainelMenuLayout.setHorizontalGroup(
            PainelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BtnInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
            .addComponent(BtnManterPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
            .addComponent(BtnManterConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
            .addComponent(BtnManterPsicologo, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
            .addComponent(BtnSair, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
        );
        PainelMenuLayout.setVerticalGroup(
            PainelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelMenuLayout.createSequentialGroup()
                .addComponent(BtnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(BtnManterPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(BtnManterConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(BtnManterPsicologo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(BtnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 636, Short.MAX_VALUE))
        );

        getContentPane().add(PainelMenu, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void clearAlterarR() {
        //limpar a tela
        txtNome5.setText(null);
        txtEmail4.setText(null);
        txtCPF4.setText(null);
        estadocivil4.setSelectedIndex(0);
        DataNasc4.clear();
        Sexo4.setSelectedIndex(0);
        TxtProfissao4.setText(null);
        TxtReligiao4.setText(null);
        TxtEscolaridade4.setText(null);
        TxtEndereco4.setText(null);
        TxtCidade4.setText(null);
        TxtTelefone10.setText(null);
        TxtTelefone11.setText(null);
    }
    public void ReadJTable() {

        DefaultTableModel model = (DefaultTableModel) JTPacientes.getModel();

        model.setNumRows(0);
        ViewsDAO vwdao = new ViewsDAO();
        Object[] linha = null;
        String fones = null;
        String[] fones2 = null;
        for (Vw_TelefonesPacientes vw : vwdao.ReadTelefonesPacientesADM()) {
            fones = vw.getTelefone().getNumero();
            if (fones.contains(",")) {

                fones2 = fones.split(",");
                linha = new Object[]{
                    vw.getPaciente().getCodPaciente(),
                    vw.getPaciente().getNome_Completo(),
                    vw.getPaciente().getEmail(),
                    fones2[0],
                    fones2[1],
                    vw.getPaciente().isDeletado()
                };
            } else {
                linha = new Object[]{
                    vw.getPaciente().getCodPaciente(),
                    vw.getPaciente().getNome_Completo(),
                    vw.getPaciente().getEmail(),
                    vw.getTelefone().getNumero(),
                    null,
                    vw.getPaciente().isDeletado()
                };

            }
            model.addRow(linha);
            fones = null;
            fones2 = null;

        }
    }

    public void ReadJTableBusca(String Busca) {

        DefaultTableModel model = (DefaultTableModel) JTPacientes.getModel();

        model.setNumRows(0);

        ViewsDAO vwdao = new ViewsDAO();
        Object[] linha = null;
        String fones = null;
        String[] fones2 = null;
        for (Vw_TelefonesPacientes vw : vwdao.BuscaManterPacienteADMOA(Busca)) {
            fones = vw.getTelefone().getNumero();
            if (fones.contains(",")) {

                fones2 = fones.split(",");
                linha = new Object[]{
                    vw.getPaciente().getCodPaciente(),
                    vw.getPaciente().getNome_Completo(),
                    vw.getPaciente().getEmail(),
                    fones2[0],
                    fones2[1],
                    vw.getPaciente().isDeletado()
                };
            } else {
                linha = new Object[]{
                    vw.getPaciente().getCodPaciente(),
                    vw.getPaciente().getNome_Completo(),
                    vw.getPaciente().getEmail(),
                    vw.getTelefone().getNumero(),
                    null,
                    vw.getPaciente().isDeletado()
                };

            }
            model.addRow(linha);
            fones = null;
            fones2 = null;

        }
    }

 

    private void JTPacientesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTPacientesKeyReleased
        // TODO add your handling code here:
        if (JTPacientes.getSelectedRow() != -1) {
            int modelRow = JTPacientes.convertRowIndexToModel(JTPacientes.getSelectedRow());
            int value = (Integer) JTPacientes.getModel().getValueAt(modelRow, 0);
            this.codigopaciente = value;

        }
    }//GEN-LAST:event_JTPacientesKeyReleased

    private void JTPacientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTPacientesMouseClicked
        // TODO add your handling code here:
        if (JTPacientes.getSelectedRow() != -1) {
            int modelRow = JTPacientes.convertRowIndexToModel(JTPacientes.getSelectedRow());
            int value = (Integer) JTPacientes.getModel().getValueAt(modelRow, 0);
            this.codigopaciente = value;
        }
    }//GEN-LAST:event_JTPacientesMouseClicked

    private void BtnVisuAlterarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVisuAlterarDadosActionPerformed
        // TODO add your handling code here:
        if (JTPacientes.getSelectedRow() != -1) {
            int modelRow = JTPacientes.convertRowIndexToModel(JTPacientes.getSelectedRow());
            int value = (Integer) JTPacientes.getModel().getValueAt(modelRow, 0);
            this.codigopaciente = value;
            PacienteDAO dao = new PacienteDAO();
            ViewsDAO vwdao = new ViewsDAO();
            Paciente p = dao.ReadPaciente(codigopaciente);
            Vw_TelefonesPacientes v = new Vw_TelefonesPacientes();
            v = vwdao.ReadTelefonesPacientes(codigopaciente);
            txtNome5.setText(p.getNome_Completo());
            Date date = (Date) p.getDataNasc();

            //LocalDate localDate = date.toInstant().atZone( ZoneId.systemDefault() ).toLocalDate();
            DataNasc4.setDate(date.toLocalDate());
            //DataNasc1.setDate((LocalDate) p.getDataNasc());
            Sexo4.setSelectedItem(p.getSexo());
            estadocivil4.setSelectedItem(p.getEstadoCivil());
            TxtCidade4.setText(p.getCidade());
            txtCPF4.setText(p.getCPF());
            TxtEndereco4.setText(p.getEndereco());
            TxtProfissao4.setText(p.getProfissao());
            TxtReligiao4.setText(p.getReligiao());
            TxtEscolaridade4.setText(p.getEscolaridade());
            if (p.isDeletado()) {
                JCBDeletado.setSelectedIndex(0);
            } else {
                JCBDeletado.setSelectedIndex(1);
            }

            String fones = null;
            String[] fones2 = null;
            fones = v.getTelefone().getNumero();
            if (fones.contains(",")) {
                fones2 = fones.split(",");
                TxtTelefone10.setText(fones2[0]);
                TxtTelefone11.setText(fones2[1]);
            } else {
                TxtTelefone10.setText(fones);
                TxtTelefone11.setText("");
            }

            txtEmail4.setText(p.getEmail());
           
            JTextField textField = DataNasc4.getComponentDateTextField();

            DataNasc4.setFont(new Font("Tahoma", Font.BOLD, 18));
            ModalAlterarResolucaoMenor.setSize(826, 660);
            ModalAlterarResolucaoMenor.setModal(true);
            ModalAlterarResolucaoMenor.setLocationRelativeTo(null);
            ModalAlterarResolucaoMenor.setVisible(true);

        } else {
            JOptionPane.showMessageDialog(this, "Selecione um Paciente para Alterar", "ERRO!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BtnVisuAlterarDadosActionPerformed

    private void BtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarActionPerformed
        // TODO add your handling code here:
        //System.out.println(JCBAtributo.getSelectedIndex());
        this.ReadJTableBusca(txtBusca.getText());
    }//GEN-LAST:event_BtnBuscarActionPerformed

    private void BtnExcluirPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExcluirPacienteActionPerformed
        // TODO add your handling code here:
        if (JTPacientes.getSelectedRow() != -1) {
            int modelRow = JTPacientes.convertRowIndexToModel(JTPacientes.getSelectedRow());
            int value = (Integer) JTPacientes.getModel().getValueAt(modelRow, 0);
            this.codigopaciente = value;

            Paciente p = new Paciente();

            p.setCodPaciente(value);
            boolean status = Deletar.DPaciente(p);
            //limpar a tela
            if (!status) {
                JOptionPane.showMessageDialog(this, "Houve um problema ao Excluir o Paciente, tente novamente!", "ERRO!", JOptionPane.ERROR_MESSAGE);

            }
            
            //mostrar mensagem de sucesso
            // JOptionPane.showMessageDialog(null,"Paciente Cadastrado com Sucesso!");
            ReadJTable();

        } else {
            JOptionPane.showMessageDialog(this, "Selecione um Paciente para alterar", "ERRO!", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_BtnExcluirPacienteActionPerformed

    private void JTPacientesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTPacientesMousePressed
        BtnVisuAlterarDados.setEnabled(true);
        BtnExcluirPaciente.setEnabled(true);
        if (evt.getClickCount() == 2) {
            if (JTPacientes.getSelectedRow() != -1) {
                int modelRow = JTPacientes.convertRowIndexToModel(JTPacientes.getSelectedRow());
                int value = (Integer) JTPacientes.getModel().getValueAt(modelRow, 0);
                this.codigopaciente = value;
                PacienteDAO dao = new PacienteDAO();
                ViewsDAO vwdao = new ViewsDAO();
                Paciente p = dao.ReadPaciente(codigopaciente);
                Vw_TelefonesPacientes v = new Vw_TelefonesPacientes();
                v = vwdao.ReadTelefonesPacientes(codigopaciente);
                txtNome5.setText(p.getNome_Completo());
                Date date = (Date) p.getDataNasc();

                //LocalDate localDate = date.toInstant().atZone( ZoneId.systemDefault() ).toLocalDate();
                DataNasc4.setDate(date.toLocalDate());
                //DataNasc1.setDate((LocalDate) p.getDataNasc());
                Sexo4.setSelectedItem(p.getSexo());
                estadocivil4.setSelectedItem(p.getEstadoCivil());
                TxtCidade4.setText(p.getCidade());
                txtCPF4.setText(p.getCPF());
                TxtEndereco4.setText(p.getEndereco());
                TxtProfissao4.setText(p.getProfissao());
                TxtReligiao4.setText(p.getReligiao());
                TxtEscolaridade4.setText(p.getEscolaridade());
                if (p.isDeletado()) {
                    JCBDeletado.setSelectedIndex(0); 
                   
                } else {
                    JCBDeletado.setSelectedIndex(0); 
                }
                String fones = null;
                String[] fones2 = null;
                fones = v.getTelefone().getNumero();
                if (fones.contains(",")) {
                    fones2 = fones.split(",");
                    TxtTelefone10.setText(fones2[0]);
                    TxtTelefone11.setText(fones2[1]);
                } else {
                    TxtTelefone10.setText(fones);
                    TxtTelefone11.setText("");
                }

                txtEmail4.setText(p.getEmail());
               
                JTextField textField = DataNasc4.getComponentDateTextField();

                DataNasc4.setFont(new Font("Tahoma", Font.BOLD, 18));
                ModalAlterarResolucaoMenor.setSize(826, 660);
                ModalAlterarResolucaoMenor.setModal(true);
                ModalAlterarResolucaoMenor.setLocationRelativeTo(null);
                ModalAlterarResolucaoMenor.setVisible(true);

            } else {
                JOptionPane.showMessageDialog(this, "Selecione um Paciente para Alterar", "ERRO!", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_JTPacientesMousePressed

    private void txtBuscaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscaKeyTyped
        this.ReadJTableBusca(txtBusca.getText());
    }//GEN-LAST:event_txtBuscaKeyTyped

    private void txtNome5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNome5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNome5ActionPerformed

    private void txtNome5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNome5KeyTyped
        char c = evt.getKeyChar();
        if (Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_txtNome5KeyTyped

    private void BtnSalvarAlteracoesNovo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalvarAlteracoesNovo3ActionPerformed
        boolean dadosvalidos = true;
        String oldJCB = (String) JCBDeletado.getSelectedItem();
        Paciente p = new Paciente();
        PacienteDAO dao = new PacienteDAO();
        Telefone tf = new Telefone();
        Telefone tf2 = new Telefone();
        TelefoneDAO tfdao = new TelefoneDAO();
        String msg = "Existem campos com formatos Inválidos\n\nFavor Verificar os campos:";
        String cpf = "";
        try {
            txtCPF4.commitEdit();
        } catch (ParseException ex) {
            Logger.getLogger(ManterPaciente1.class.getName()).log(Level.SEVERE, null, ex);
        }

        if ((String) txtCPF4.getValue() != null) {
            cpf = (String) txtCPF4.getValue();
            cpf = cpf.replace(".", "").replace("-", "");
        }
        if (!Validar.vCamposVazios(this, txtNome5, txtEmail4, cpf, DataNasc4, TxtTelefone10)) {
            p.setCodPaciente(codigopaciente);
            if (Validar.vNome(txtNome5.getText())) {
                p.setNome_Completo(txtNome5.getText());
            } else {
                dadosvalidos = false;
                msg += "\nNome Invalido: " + txtNome5.getText();
            }

            if (Validar.vEmail(txtEmail4.getText())) {
                p.setEmail(txtEmail4.getText());
            } else {
                dadosvalidos = false;
                msg += "\nEmail Invalido: " + txtEmail4.getText();
            }

            if (Validar.vCPF(cpf)) {
                p.setCPF(cpf);
            } else {
                dadosvalidos = false;
                msg += "\nCPF Invalido: " + cpf;
            }

            p.setEstadoCivil((String) estadocivil4.getSelectedItem());
            p.setSexo((String) Sexo4.getSelectedItem());
            p.setProfissao(TxtProfissao4.getText());
            p.setReligiao(TxtReligiao4.getText());
            p.setEscolaridade(TxtEscolaridade4.getText());
            p.setEndereco(TxtEndereco4.getText());
            p.setCidade(TxtCidade4.getText());

            //java.util.Date date = new java.util.Date();
            Object param = DataNasc4.getDate();

            p.setDataNasc(param);

            if (Validar.vTelefone(TxtTelefone10.getText())) {
                tf.setNumero(TxtTelefone10.getText());
            } else {
                dadosvalidos = false;
                msg += "\nNúmero de Telefone Invalido: " + TxtTelefone10.getText() + "\nO Número deve ser no formato xxxxxxxxxxx";
            }
            if (!TxtTelefone11.getText().isEmpty()) {
                if (Validar.vTelefone(TxtTelefone11.getText())) {
                    tf2.setNumero(TxtTelefone11.getText());
                } else {
                    dadosvalidos = false;
                    msg += "\nNúmero de Telefone 2 Invalido: " + TxtTelefone11.getText() + "\nO Número deve ser no formato xxxxxxxxxxx";
                }
            }
            if (dadosvalidos) {
                if(JCBDeletado.getSelectedIndex() == 0){
                    p.setDeletado(true);
                }else{
                    p.setDeletado(false);
                }
                if (dao.Update(p)) {
                    
                    p = dao.ReadPaciente(p.getCPF());

                    tf.setPaciente(p);
                    List<Telefone> t = new ArrayList<>();
                    t = tfdao.Read(p.getCodPaciente());
                    t.get(0).setNumero(TxtTelefone10.getText());
                    if (tfdao.UpdateTPaciente(t.get(0))) {
                        if (t.size() == 2) {
                            t.get(1).setNumero(TxtTelefone11.getText());
                            tfdao.UpdateTPaciente(t.get(1));
                        }
                        if (!TxtTelefone11.getText().isEmpty() && t.size() == 1) {
                            tf2.setPaciente(p);
                            tf2.setNumero(TxtTelefone11.getText());
                            tfdao.CreatePc(tf2);

                        }
                        //JOptionPane.showMessageDialog(this, "Paciente " + p.getNome_Completo() + " Atualizado com sucesso");
                        //this.clear();
                        String str = "Paciente " + p.getNome_Completo() + " Atualizado com sucesso";
                        if(oldJCB != JCBDeletado.getSelectedItem()){
                            Restaurar.RestaurarTelefonesPaciente(p.getCodPaciente());
                        }
                        clearAlterarR();
                        ModalAlterarResolucaoMenor.dispose();
                    }

                }

                //mostrar mensagem de sucesso
                // JOptionPane.showMessageDialog(null,"Paciente Cadastrado com Sucesso!");
               

            } else {
                JOptionPane.showMessageDialog(this, msg, "ERRO!", JOptionPane.ERROR_MESSAGE);
            }
        }
        ReadJTable();
    }//GEN-LAST:event_BtnSalvarAlteracoesNovo3ActionPerformed

    private void BtnCancelar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelar3ActionPerformed
        ModalAlterarResolucaoMenor.dispose();
    }//GEN-LAST:event_BtnCancelar3ActionPerformed

    private void estadocivil4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadocivil4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estadocivil4ActionPerformed

    private void Sexo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sexo4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sexo4ActionPerformed

    private void TxtEscolaridade4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtEscolaridade4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtEscolaridade4ActionPerformed

    private void TxtTelefone10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtTelefone10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtTelefone10ActionPerformed

    private void TxtTelefone10KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtTelefone10KeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_TxtTelefone10KeyTyped

    private void TxtTelefone11KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtTelefone11KeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_TxtTelefone11KeyTyped

    private void txtCPF4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCPF4KeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_txtCPF4KeyTyped

    private void BtnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInicioActionPerformed
        TelaPrincipalAdm mp1 = new TelaPrincipalAdm();
        Util.SizeJanela(mp1);
        this.dispose();
    }//GEN-LAST:event_BtnInicioActionPerformed

    private void BtnManterPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnManterPacienteActionPerformed
        M mp1 = new M();
        Util.SizeJanela(mp1);
        this.dispose();
    }//GEN-LAST:event_BtnManterPacienteActionPerformed

    private void BtnManterConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnManterConsultaActionPerformed
        ManterConsultasAdm mc = new ManterConsultasAdm();
        Util.SizeJanela(mc);
        this.dispose();
    }//GEN-LAST:event_BtnManterConsultaActionPerformed

    private void BtnManterPsicologoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnManterPsicologoActionPerformed
        ManterPsiAdm mp = new ManterPsiAdm();
        mp.setVisible(true);
        Util.SizeJanela(mp);
        this.dispose();
    }//GEN-LAST:event_BtnManterPsicologoActionPerformed

    private void BtnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSairActionPerformed
        TelaLogin  tl = new TelaLogin();
        tl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManterPacienteAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManterPacienteAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManterPacienteAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManterPacienteAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManterPacienteAdm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBuscar;
    private javax.swing.JButton BtnCancelar3;
    private javax.swing.JButton BtnExcluirPaciente;
    private javax.swing.JButton BtnInicio;
    private javax.swing.JButton BtnManterConsulta;
    private javax.swing.JButton BtnManterPaciente;
    private javax.swing.JButton BtnManterPsicologo;
    private javax.swing.JButton BtnSair;
    private javax.swing.JButton BtnSalvarAlteracoesNovo3;
    private javax.swing.JButton BtnVisuAlterarDados;
    private com.github.lgooddatepicker.components.DatePicker DataNasc4;
    private javax.swing.JComboBox<String> JCBDeletado;
    private javax.swing.JTable JTPacientes;
    private javax.swing.JLabel LabelCPF4;
    private javax.swing.JLabel LabelCidade12;
    private javax.swing.JLabel LabelCidade13;
    private javax.swing.JLabel LabelCidade14;
    private javax.swing.JLabel LabelEmail5;
    private javax.swing.JLabel LabelEscolaridade4;
    private javax.swing.JLabel LabelEstadoCivil4;
    private javax.swing.JLabel LabelNome3;
    private javax.swing.JLabel LabelProfissao4;
    private javax.swing.JLabel LabelReligiao4;
    private javax.swing.JDialog ModalAlterarResolucaoMenor;
    private javax.swing.JPanel PainelIdentificacaoPessoal7;
    private javax.swing.JPanel PainelIdentificacaoPessoal8;
    private javax.swing.JPanel PainelMenu;
    private javax.swing.JComboBox<String> Sexo4;
    private javax.swing.JTextField TxtCidade4;
    private javax.swing.JTextField TxtEndereco4;
    private javax.swing.JTextField TxtEscolaridade4;
    private javax.swing.JTextField TxtProfissao4;
    private javax.swing.JTextField TxtReligiao4;
    private javax.swing.JTextField TxtTelefone10;
    private javax.swing.JTextField TxtTelefone11;
    private javax.swing.JComboBox<String> estadocivil4;
    private LIB.JEImagePanel jEImagePanel1;
    private LIB.JEImagePanel jEImagePanel8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField txtBusca;
    private javax.swing.JFormattedTextField txtCPF4;
    private javax.swing.JTextField txtEmail4;
    private javax.swing.JTextField txtNome5;
    // End of variables declaration//GEN-END:variables
}
